# Generated by Django 4.0.2 on 2022-02-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('document', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, null=True)),
                ('type_p', models.CharField(choices=[('Persona Natural', 'Persona Natural'), ('Persona Jurídica', 'Persona Jurídica')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('document', models.IntegerField(primary_key=True, serialize=False)),
                ('matricula', models.IntegerField(null=True)),
                ('category', models.CharField(choices=[('Urbano', 'Urbano'), ('Rural', 'Rural')], max_length=200, null=True)),
                ('Location', models.CharField(blank=True, max_length=200, null=True)),
                ('owner', models.ManyToManyField(blank=True, related_name='predios', to='predioapp.Owner')),
            ],
        ),
    ]
